name: java-docker-ci

on:
  push:
    branches:
      - 'master'
  workflow_dispatch:      

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: chrbudtz/devops:latest,
      -
        name: install caprover cli
        run: npm install -g caprover
      - 
        name: Deploy app
        env: 
          APP_NAME: 'devopse22'
          APP_URL: 'https://captain.caprover.diplomportal.dk/'
          CAPROVER_APP_TOKEN: ${{secrets.CAPROVER_PASSWORD}}
          IMAGE_NAME: 'chrbudtz/devops'
        run: 
         'caprover deploy --caproverUrl=$APP_URL --caproverPassword $CAPROVER_APP_TOKEN --imageName=$IMAGE_NAME --appName=$APP_NAME'
