name: java-docker-ci

on:
  push:
    branches:
      - 'master'
      - 'dev'
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # Initialize Emumlation
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      # Setup Docker
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      # Login to DockerHub
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      # Build Docker image and push to DockerHub
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: chrbudtz/devops:${{github.run_number}},
      # Install caprover cli
      - name: install caprover cli
        run: npm install -g caprover
      # Trigger deploy on Caprover instance
      - name: Deploy app
        env: 
          APP_NAME: 'devopse22'
          APP_URL: 'https://devopse22.diplomportal.dk/'
          IMAGE_NAME: 'chrbudtz/devops:${{github.run_number}}'
        run: 
         'caprover deploy --caproverUrl=$APP_URL --caproverPassword=${{ secrets.CAPROVER_PASSWORD }} --imageName=$IMAGE_NAME --appName=$APP_NAME'
